Psyche/config/routes.rb
PsycheCMS::Application.routes.draw do

  get "email/index"

  root :to => "router#index"

  resources :users
  resources :pages

  get "posts/postfeed"

  resources :posts
 
  get "admin/index"
  get "admin/login"
  get "admin/dashboard"
  post "admin/check"
  get "admin/addpage"
  get "admin/addpost"
  get "admin/pages"
  get "admin/edit"

  get "settings/index"

  get "router/index"

  get "error/page_not_found"
  get "error/post_not_found"
  get "error/missing_template"
  get"error/no_content"
  get "error/security_violation"
  match '*a', :to=>'router#index'

 

end

Psyche/app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :template %><br />
    <%= f.text_field :template %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Psyche/app/views/pages/create.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "create.html" %>

Psyche/app/views/pages/edit.html.erb
<% if flash[:pagesaved] != nil %>


<% end %>
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

Psyche/app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Template</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= page.title %></td>
    <td><%= page.content %></td>
    <td><%= page.template %></td>
    <td><%= link_to 'Show', page %></td>
    <td><%= link_to 'Edit', edit_page_path(page) %></td>
    <td><%= link_to 'Destroy', page, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Page', new_page_path %>

Psyche/app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

Psyche/app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @page.title %>
</p>

<p>
  <b>Content:</b>
  <%= @page.content %>
</p>

<p>
  <b>Template:</b>
  <%= @page.template %>
</p>


<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>